os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_script:
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter test --coverage test/*
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache


#language: node_js
#node_js:
# - "node"
#before_install:
#  - pip install --user codecov
#before_script:
# - gem install coveralls-lcov
#script:
# - ./flutter/bin/flutter test --coverage test/*
#after_success:
#  - codecov --file coverage/lcov.info --disable search
#  - coveralls-lcov coverage/lcov.info
#codecov:
#  token: 032f59ee-4fcd-47e6-8b22-47930fe3e7f2


#language: android 
#jdk: oraclejdk8

#components: 
#  - tools
#  - tools
#  - platform-tools
#  - extra-google-google-play-services
#  - extra

# language: node_js
# node_js: 
# -11.6.0
# cache: yarn

# install: 
#   - yarn install

# script: 
#   - yarn test
#   - yarn run build

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   on:
#     branch: gh_pages
